#!/bin/sh

mkdir -v -p $THEOS/frameworks
rm -rf $THEOS/frameworks/SettingsKit.framework
cp -r .theos/obj/SettingsKit.framework $THEOS/frameworks

rm -rf $THEOS/include/SettingsKit
mkdir -v -p $THEOS/include/SettingsKit/
mkdir -v -p $THEOS/include/SettingsKit/Resources
mkdir -v -p $THEOS/include/SettingsKit/Preferences
cp -v -f *.h $THEOS/include/SettingsKit/
cp -v -f *.m $THEOS/include/SettingsKit/
cp -v -f Resources/* $THEOS/include/SettingsKit/Resources/
cp -v -f Preferences/* $THEOS/include/SettingsKit/Preferences
